    server {
        server_name                     YOURDOMAIN;
        ssl_certificate                 ../path/to/chained.pem;
        ssl_certificate_key             ../path/to/private.pem;
        http2  on;
        listen                          [::]:443 ssl;
        listen                          443 ssl;
        listen                          [::]:443 quic;
        listen                          443 quic;
        # Place specific proxy locations first to ensure they are matched before the general root block
        location /ws/ {
            proxy_http_version          1.1;
            proxy_pass                  http://YOURIP:3001/;
            proxy_set_header            Connection "Upgrade";
            proxy_set_header            Host $host;
            proxy_set_header            Upgrade $http_upgrade;
        }
        # TURN credentials API
        location /api/get-turn-credentials {
            proxy_pass                  http://YOURIP:3001/api/get-turn-credentials;
            proxy_set_header            Host $host;
        }
        # regex location for the web application's root pages
        location ~^/(room|)$ {
            #if HTTP/3 is not supported uncomment following line
            add_header                  Alt-Svc 'h3=":443";ma=86400;persist=1';
            add_header                  Permissions-Policy "geolocation=()" always;
            add_header                  Referrer-Policy same-origin always;
            #add_header                  Strict-Transport-Security 'includeSubDomains;max-age=63072000;preload' always;
            add_header                  X-Content-Type-Options nosniff always;
            add_header                  X-Frame-Options sameorigin always;
            add_header                  X-Xss-Protection '1;mode=block' always;
            error_log                   logs/error;
            expires                     0;
            include                     fastcgi_params;
            index                       index.php;
            fastcgi_pass                unix:/run/php/php8.5-fpm.sock;
            fastcgi_param               SCRIPT_FILENAME $document_root/index.php;
            root                        domains/YOURDOMAIN;
            try_files                   /index.php =444;
        }
        # The general location block should be last as a fallback
        location / {
            index                       index.php;
            root                        domains/YOURDOMAIN;
        }
    }