listening-port=3480
realm=YOURDOMAIN
use-auth-secret
static-auth-secret=YOURAUTHSECRET

# Your server's public IP.
external-ip=YOURIPv4,[YOURIPv6]

# Relay port range - ensure this is open in your firewall (UDP)
min-port=49152
max-port=65535

# Security & Logging
log-file=/var/log/turnserver/webrtc.log
verbose
denied-peer-ip=127.0.0.1
denied-peer-ip=::1